### ISSUE TITLE
Middleware Error Trace Produced

### ISSUE THREAD

**Issue by aspencerpsu** [FHIR/fhir.js#129]
Version 0.0.20
Platform Linux(Ubuntu)

Hey I'm trying to running a smart client on one of lx boxes and the following ugly stack trace is outputed
```
     Cannot read property 'trim' of undefined
     at buildPathPart (/app/checkItOut/node_modules/fhir.js/src/middlewares/url.js:33:30)
     at new_chain (/app/checkItOut/node_modules/fhir.js/src/middlewares/url.js:45:62)
     at new_chain (/app/checkItOut/node_modules/fhir.js/src/middlewares/url.js:45:32)
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:67:30
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:58:28
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:58:28
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:58:28
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/http.js:27:20
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:56:28
     at /app/checkItOut/node_modules/fhir.js/src/middlewares/core.js:58:28
```

Anyone else getting this?

**Comment by mike1pol** [comment]
Please send your call stack.
Most likely this is due to the fact that instead of a string, comes a function, null or undefined
